services:
  project:
    build: .
    container_name: project
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: /bin/bash -c "python app/ingest/run_on_startup.py && streamlit run streamlit_app.py --server.port=8501"